version: "3"
services:
  backend:
    build:
      context: .
      dockerfile: backend.dockerfile
      args:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        DB_SERVER_HOST: ${DB_SERVER_HOST}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    container_name: ${CONTAINER_NAME}-backend.local
    restart: always
    volumes:
      - .zdata:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - zabbix-network

  frontend:
    build:
      context: .
      dockerfile: frontend.dockerfile
      args:
        ZBX_SERVER_HOST: ${ZBX_SERVER_HOST}
        PHP_TZ: ${PHP_TZ}
        DB_SERVER_HOST: ${DB_SERVER_HOST}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    container_name: ${CONTAINER_NAME}-frontend.local
    restart: always
    volumes:
      - .zconfig:/etc/zabbix
    ports:
      - 10050:10050
      - 10051:10051
      - 18080:80
      - 14330:433
    networks:
      - zabbix-network

volumes:
  .zdata:
  .zconfig:

networks:
  zabbix-network: